# Generated by Django 2.2.6 on 2019-12-12 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0002_rating_wallpaper'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallpaper',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
