# Generated by Django 2.2.6 on 2019-12-12 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0004_auto_20191212_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallpaper',
            name='rate_avg',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
