# Generated by Django 2.2.6 on 2019-12-12 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0005_auto_20191212_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallpaper',
            name='tags',
            field=models.ManyToManyField(to='wallpaper.Tag'),
        ),
    ]
