# Generated by Django 2.2.6 on 2019-12-12 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0006_auto_20191212_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallpaper',
            name='image',
            field=models.ImageField(upload_to='wallpapers/%Y/%d'),
        ),
        migrations.AlterField(
            model_name='wallpaper',
            name='thumbnail',
            field=models.ImageField(editable=False, upload_to='thumbs/%Y/%d'),
        ),
    ]
