# Generated by Django 3.0 on 2019-12-12 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0007_auto_20191212_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default=0, help_text='Please make sure the image size should be 400 * 200', upload_to='category/%Y/%d'),
            preserve_default=False,
        ),
    ]
