# Generated by Django 3.0 on 2019-12-17 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0008_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallpaper',
            name='name',
            field=models.CharField(db_index=True, default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wallpaper',
            name='slug',
            field=models.SlugField(default=0),
            preserve_default=False,
        ),
    ]
